services:

  backend:
    build:
      context: ./backend
    container_name: tikkamasala-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/tikkamasala-data/tikkamasala.db:/app/tikkamasala.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: tikkamasala-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped